#!/bin/bash
# Demo script to show vendor filter features

echo "==================================================================="
echo "KURMI VENDOR FILTER - Remove Unwanted Vendors"
echo "==================================================================="
echo ""
echo "PURPOSE:"
echo "  After extracting workspace files, filter out unwanted vendors"
echo "  to keep only the vendors you need in your workspace."
echo ""
echo "==================================================================="
echo ""
echo "COMPLETE WORKFLOW:"
echo ""
echo "Step 1: Extract workspace"
echo "   python3 kurmi_workspace_parser.py"
echo ""
echo "Step 2: Filter vendors"
echo "   python3 kurmi_vendor_filter.py"
echo ""
echo "==================================================================="
echo ""
echo "WHAT THE VENDOR FILTER DOES:"
echo ""
echo "1. SCANS all category folders:"
echo "   - service_definitions/"
echo "   - service_inference/"
echo "   - quickfeatures/"
echo "   - connectors/"
echo "   - etc."
echo ""
echo "   NOTE: scenarios/ directory is excluded from vendor scanning"
echo ""
echo "2. IDENTIFIES all vendor subdirectories in each category:"
echo "   - Cisco/"
echo "   - Microsoft/"
echo "   - BroadWorks/"
echo "   - webex/"
echo "   - etc."
echo ""
echo "3. DISPLAYS vendor distribution:"
echo "   - Shows which vendors exist in which categories"
echo "   - Shows total number of categories per vendor"
echo ""
echo "4. INTERACTIVE SELECTION:"
echo "   - No vendors selected by default"
echo "   - Select the vendors you want to KEEP"
echo "   - Toggle vendors on/off as needed"
echo ""
echo "5. REMOVES non-selected vendors:"
echo "   - Deletes all directories for unselected vendors"
echo "   - Shows statistics of removed vendors"
echo "   - Cannot be undone!"
echo ""
echo "==================================================================="
echo ""
echo "EXAMPLE SCENARIOS:"
echo ""
echo "==================================================================="
echo "Scenario 1: Cisco On-Premises Deployment (Use Preset)"
echo "==================================================================="
echo ""
echo "You have a Cisco on-premises deployment and need core infrastructure."
echo ""
echo "Solution:"
echo "  1. Run: python3 kurmi_vendor_filter.py"
echo "  2. Type: cisco"
echo "  3. Confirm: press Enter"
echo "  4. Confirm removal: type 'yes'"
echo ""
echo "Result:"
echo "  ✓ Keeps: Allocations, Cisco, Directory, ForgottenPassword,"
echo "          Technical, User, WrongAttempt, common, licensing"
echo "  ✓ Removes all cloud/third-party vendors"
echo ""
echo "==================================================================="
echo "Scenario 2: Microsoft 365/Teams Deployment (Use Preset)"
echo "==================================================================="
echo ""
echo "You have a Microsoft 365/Teams deployment and need Microsoft services."
echo ""
echo "Solution:"
echo "  1. Run: python3 kurmi_vendor_filter.py"
echo "  2. Type: microsoft"
echo "  3. Confirm: press Enter"
echo "  4. Confirm removal: type 'yes'"
echo ""
echo "Result:"
echo "  ✓ Keeps: Microsoft, m365, office365, office365graph"
echo "  ✓ Removes all other vendor directories"
echo ""
echo "==================================================================="
echo "Scenario 3: Hybrid Deployment (Combine Multiple Presets)"
echo "==================================================================="
echo ""
echo "You have both Cisco on-prem and Microsoft cloud services."
echo ""
echo "Solution:"
echo "  1. Run: python3 kurmi_vendor_filter.py"
echo "  2. Type: cisco"
echo "  3. Type: microsoft"
echo "  4. Confirm: press Enter"
echo "  5. Confirm removal: type 'yes'"
echo ""
echo "Result:"
echo "  ✓ Keeps all Cisco vendors (9 vendors)"
echo "  ✓ Keeps all Microsoft vendors (4 vendors)"
echo "  ✓ Total: 13 vendors selected"
echo "  ✓ Removes all other vendor directories"
echo ""
echo "==================================================================="
echo "Scenario 4: Specific Vendors Only (Manual Selection)"
echo "==================================================================="
echo ""
echo "You only need Cisco and webex files."
echo ""
echo "Solution:"
echo "  1. Run: python3 kurmi_vendor_filter.py"
echo "  2. Select Cisco and webex: type '4,13'"
echo "  3. Confirm: press Enter"
echo "  4. Confirm removal: type 'yes'"
echo ""
echo "Result:"
echo "  ✓ Only Cisco and webex files remain"
echo "  ✓ All other vendor directories removed"
echo ""
echo "==================================================================="
echo ""
echo "INTERACTIVE COMMANDS:"
echo ""
echo "  Toggle vendors:  1,3,5  or  1-10"
echo "  Select all:      all"
echo "  Deselect all:    none"
echo "  Presets:"
echo "    - cisco         (Cisco on-premises infrastructure)"
echo "    - microsoft     (Microsoft cloud services)"
echo "    - webex         (Webex collaboration & contact center)"
echo "  Continue:        Enter or 'done'"
echo "  Cancel:          q"
echo ""
echo "==================================================================="
echo ""
echo "SAFETY FEATURES:"
echo ""
echo "  ✓ Shows which vendors will be removed before deletion"
echo "  ✓ Asks for confirmation before removing"
echo "  ✓ Can cancel at any time (type 'q')"
echo "  ✓ Logs all operations to vendor_filter.log"
echo ""
echo "⚠️  WARNING: Deletion cannot be undone!"
echo "    Make a backup if you want to preserve original extraction"
echo ""
echo "==================================================================="
echo ""
echo "To see the full help menu:"
echo "   python3 kurmi_vendor_filter.py --help"
echo ""
echo "==================================================================="
